// 47 dataItems  include alarm also
const dataItems = [ { '$': { category: 'EVENT', id: 'avail', type: 'AVAILABILITY' },
    path: '//Devices//Device[@name="VMC-3Axis"]//DataItem[@type="AVAILABILITY"]' },
  { '$':
     { category: 'EVENT',
       id: 'dev000_asset_chg',
       type: 'ASSET_CHANGED' },
    path: '//Devices//Device[@name="VMC-3Axis"]//DataItem[@type="ASSET_CHANGED"]' },
  { '$':
     { category: 'EVENT',
       id: 'dev000_asset_rem',
       type: 'ASSET_REMOVED' },
    path: '//Devices//Device[@name="VMC-3Axis"]//DataItem[@type="ASSET_REMOVED"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'c2',
       name: 'Sspeed',
       nativeUnits: 'REVOLUTION/MINUTE',
       subType: 'ACTUAL',
       type: 'SPINDLE_SPEED',
       units: 'REVOLUTION/MINUTE' },
    Source: [ 'spindle_speed' ],
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Rotary//DataItem[@type="SPINDLE_SPEED" and @subType="ACTUAL"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'c3',
       name: 'Sovr',
       nativeUnits: 'PERCENT',
       subType: 'OVERRIDE',
       type: 'SPINDLE_SPEED',
       units: 'PERCENT' },
    Source: [ 'SspeedOvr' ],
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Rotary//DataItem[@type="SPINDLE_SPEED" and @subType="OVERRIDE"]' },
  { '$':
     { category: 'EVENT',
       id: 'cm',
       name: 'Cmode',
       type: 'ROTARY_MODE' },
    Constraints: [ { Value: [ 'SPINDLE' ] } ],
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Rotary//DataItem[@type="ROTARY_MODE"]' },
  { '$': { category: 'CONDITION', id: 'Cloadc', type: 'LOAD' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Rotary//DataItem[@type="LOAD"]' },
  { '$': { category: 'CONDITION', id: 'Csystem', type: 'SYSTEM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Rotary//DataItem[@type="SYSTEM"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'cl3',
       name: 'Cload',
       nativeUnits: 'PERCENT',
       type: 'LOAD',
       units: 'PERCENT' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Rotary//DataItem[@type="LOAD"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'x2',
       name: 'Xact',
       nativeUnits: 'MILLIMETER',
       subType: 'ACTUAL',
       type: 'POSITION',
       units: 'MILLIMETER' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="POSITION" and @subType="ACTUAL"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'x3',
       name: 'Xcom',
       nativeUnits: 'MILLIMETER',
       subType: 'COMMANDED',
       type: 'POSITION',
       units: 'MILLIMETER' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="POSITION" and @subType="COMMANDED"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'n3',
       name: 'Xload',
       nativeUnits: 'PERCENT',
       type: 'LOAD',
       units: 'PERCENT' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="LOAD"]' },
  { '$': { category: 'CONDITION', id: 'Xloadc', type: 'LOAD' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="LOAD"]' },
  { '$': { category: 'CONDITION', id: 'Xsystem', type: 'SYSTEM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="SYSTEM"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'y2',
       name: 'Yact',
       nativeUnits: 'MILLIMETER',
       subType: 'ACTUAL',
       type: 'POSITION',
       units: 'MILLIMETER' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="POSITION" and @subType="ACTUAL"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'y3',
       name: 'Ycom',
       nativeUnits: 'MILLIMETER',
       subType: 'COMMANDED',
       type: 'POSITION',
       units: 'MILLIMETER' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="POSITION" and @subType="COMMANDED"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'y4',
       name: 'Yload',
       nativeUnits: 'PERCENT',
       type: 'LOAD',
       units: 'PERCENT' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="LOAD"]' },
  { '$': { category: 'CONDITION', id: 'Yloadc', type: 'LOAD' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="LOAD"]' },
  { '$': { category: 'CONDITION', id: 'Ysystem', type: 'SYSTEM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="SYSTEM"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'z2',
       name: 'Zact',
       nativeUnits: 'MILLIMETER',
       subType: 'ACTUAL',
       type: 'POSITION',
       units: 'MILLIMETER' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="POSITION" and @subType="ACTUAL"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'z3',
       name: 'Zcom',
       nativeUnits: 'MILLIMETER',
       subType: 'COMMANDED',
       type: 'POSITION',
       units: 'MILLIMETER' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="POSITION" and @subType="COMMANDED"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'z4',
       name: 'Zload',
       nativeUnits: 'PERCENT',
       type: 'LOAD',
       units: 'PERCENT' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="LOAD"]' },
  { '$': { category: 'CONDITION', id: 'Zloadc', type: 'LOAD' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="LOAD"]' },
  { '$': { category: 'CONDITION', id: 'Zsystem', type: 'SYSTEM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Axes//Linear//DataItem[@type="SYSTEM"]' },
  { '$': { category: 'EVENT', id: 'cn2', name: 'block', type: 'BLOCK' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="BLOCK"]' },
  { '$':
     { category: 'EVENT',
       id: 'cn3',
       name: 'mode',
       type: 'CONTROLLER_MODE' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="CONTROLLER_MODE"]' },
  { '$': { category: 'EVENT', id: 'cn4', name: 'line', type: 'LINE' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="LINE"]' },
  { '$': { category: 'EVENT', id: 'cn5', name: 'program', type: 'PROGRAM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="PROGRAM"]' },
  { '$':
     { category: 'EVENT',
       id: 'cn6',
       name: 'execution',
       type: 'EXECUTION' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="EXECUTION"]' },
  { '$':
     { category: 'EVENT',
       id: 'cnt1',
       name: 'tool_id',
       type: 'TOOL_ID' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="TOOL_ID"]' },
  { '$': { type: 'ALARM', category: 'EVENT', id: 'path_39', name: 'alarm' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="ALARM"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'Ppos',
       nativeUnits: 'MILLIMETER_3D',
       subType: 'ACTUAL',
       type: 'PATH_POSITION',
       units: 'MILLIMETER_3D' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="PATH_POSITION" and @subType="ACTUAL"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'Frt',
       nativeUnits: 'MILLIMETER/SECOND',
       type: 'PATH_FEEDRATE',
       units: 'MILLIMETER/SECOND' },
    Source: [ 'path_feedrate' ],
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="PATH_FEEDRATE"]' },
  { '$':
     { category: 'SAMPLE',
       id: 'Fovr',
       nativeUnits: 'PERCENT',
       type: 'PATH_FEEDRATE',
       units: 'PERCENT' },
    Source: [ 'feed_ovr' ],
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//Path//DataItem[@type="PATH_FEEDRATE"]' },
  { '$': { category: 'EVENT', id: 'msg', type: 'MESSAGE' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//DataItem[@type="MESSAGE"]' },
  { '$': { category: 'EVENT', id: 'estop', type: 'EMERGENCY_STOP' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//DataItem[@type="EMERGENCY_STOP"]' },
  { '$': { category: 'CONDITION', id: 'clp', type: 'LOGIC_PROGRAM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//DataItem[@type="LOGIC_PROGRAM"]' },
  { '$': { category: 'CONDITION', id: 'motion', type: 'MOTION_PROGRAM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//DataItem[@type="MOTION_PROGRAM"]' },
  { '$': { category: 'CONDITION', id: 'system', type: 'SYSTEM' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Controller//DataItem[@type="SYSTEM"]' },
  { '$':
     { category: 'EVENT',
       id: 'p2',
       name: 'power',
       type: 'POWER_STATE' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Electric//DataItem[@type="POWER_STATE"]' },
  { '$': { category: 'CONDITION', id: 'clow', type: 'LEVEL' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Coolant//DataItem[@type="LEVEL"]' },
  { '$': { category: 'CONDITION', id: 'coolpres', type: 'PRESSURE' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Coolant//DataItem[@type="PRESSURE"]' },
  { '$': { category: 'CONDITION', id: 'filter', type: 'x:FILTER' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Coolant//DataItem[@type="x:FILTER"]' },
  { '$': { category: 'CONDITION', id: 'coolantmotor', type: 'ACTUATOR' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Coolant//DataItem[@type="ACTUATOR"]' },
  { '$': { category: 'CONDITION', id: 'hlow', type: 'LEVEL' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Hydraulic//DataItem[@type="LEVEL"]' },
  { '$': { category: 'CONDITION', id: 'hpres', type: 'PRESSURE' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Hydraulic//DataItem[@type="PRESSURE"]' },
  { '$': { category: 'CONDITION', id: 'htemp', type: 'TEMPERATURE' },
    path: '//Devices//Device[@name="VMC-3Axis"]//Systems//Hydraulic//DataItem[@type="TEMPERATURE"]' } ]

module.exports = {
  dataItems,
};
